apiVersion: v1
kind: Service
metadata:
  name: wuzapi-postgres
  namespace: wuzapi-staging
  labels:
    app: wuzapi-postgres
spec:
  type: ClusterIP
  clusterIP: None  # headless — StatefulSet usa pra DNS estável
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: wuzapi-postgres
